name: sikap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  http: ^1.2.0
  record: ^6.1.2
  path_provider: ^2.1.4
  mime: ^1.0.5
  http_parser: ^4.0.2
  file_picker: ^8.1.2
  flutter_secure_storage: ^9.2.2
  flutter_secure_storage_web: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/others/
    - assets/data/
    - assets/images/scenario_illustration/
    - assets/images/article_images/

flutter_launcher_icons:
  image_path: "assets/icons/sikap_icon.jpg"
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icons/sikap_icon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/sikap_icon.jpg"
  macos:
    generate: true
    image_path: "assets/icons/sikap_icon.jpg"
  linux:
    generate: true
    image_path: "assets/icons/sikap_icon.jpg"


